### ISSUE TITLE
Navigation dans une arborescence

### ISSUE THREAD

**Issue by AlexisMelo** [les-experts/INSA_L_Aide#1]
# Description

Lorsqu'on arrive sur la page d'accueil du site, il faudrait que l'on puisse naviguer dans une arborescence de fichiers et de dossiers. Cette arborescence ne doit pas être hard-codée mais doit être récupérée de l'arborescence d'un vrai dossier, présent quelque part dans le projet. 

# Contraintes

- Ici on ne s'occupe pas d'avoir un affichage très poussé, une issue sera ouverte pour le front
- Les dossiers vides doivent aussi être affichés
- Le chemin du fichier doit être modifiable dans l'URL pour faciliter la navigation/partage (ex : insaled.com/ananum/fiches/truc.md ou en GET insaled.com/arborescence?name=ananum/fiches/truc.md)

**Comment by Zaneriis** [comment]
On peux navifguer dans les dossier présent dans le "writable/RepositoryGit"

**Comment by Zaneriis** [comment]
On peut télécharger un fichier en cliquant dessus.
