### ISSUE TITLE
Barre de recherche fonctionnelle

### ISSUE THREAD

**Issue by AlexisMelo** [les-experts/INSA_L_Aide#5]
# Description

Le site doit avoir une barre de recherche qui permette de rentrer un mot clé et de le chercher dans tous les titres des fichiers du projet, voir dans tous les fichiers. Une fois les résultats trouvés, il faut les envoyer à la vue.
On ne s'occupe pas du front ici

# Contraintes

- Le mot clé doit être cherché dans les titres, et DANS les fichiers
- la réponse doit être très rapide

**Comment by Zaneriis** [comment]
Barre de recherche faite. Elle permet de rechercehr par rapport au nom des fichiers
